import Providers from '@/components/Providers';
import { cn } from '@/utils/cn';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className={(cn('bg-dark-background'), inter.className)}>
			<body className='min-h-screen text-white bg-dark-background antialiased'>
				<Providers>
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	);
}
